development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: 
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: 
  password: 